### ISSUE TITLE
I have some question?

### ISSUE THREAD

**Issue by adaasss** [Kaushalya/medclip#11]
Hello sir

**Comment by Kaushalya** [comment]
Hi,
The CLIP model trained on the ROCO dataset is loaded with
```
FlaxHybridCLIP.from_pretrained("flax-community/medclip-roco")
```

I have merged the code of the Streamlit app to this repo. Could you have a look at it? 
Now you can run the demo locally with 
```
streamlit run /home/kaushalya/coding/medclip/app.py
```
