### ISSUE TITLE
error when trying to load pretrained model

### ISSUE THREAD

**Issue by raulcarlomagno** [Kaushalya/medclip#20]
hello, i have this error when trying to load the model from your notebooks

![image](https://user-images.githubusercontent.com/2282315/201695555-62935a7a-8343-4163-83b1-45d569216bdd.png)

Name: transformers
Version: 4.24.0

Name: torch
Version: 1.13.0

Name: jax
Version: 0.3.24

Name: flax
Version: 0.6.1

**Comment by Kaushalya** [comment]
Thanks. `do_init` is a new parameter added to the `FlaxHybridClip`.
I have forgotten to update the Jupyter notebook. Could you please create a PR?

**Comment by raulcarlomagno** [comment]
done
https://github.com/Kaushalya/medclip/pull/21

**Comment by Kaushalya** [comment]
Thank you
