### ISSUE TITLE
can you provide a .bin or .pth format pretained medclip model?

### ISSUE THREAD

**Issue by jzssz** [Kaushalya/medclip#24]
how to transfer the  .msgpack model you provided (in https://huggingface.co/kaushalya/medclip/tree/main) to a hugging face format (such as .bin) or a pytorch format (such as .pth)?
or can you provide a .bin or .pth format pretained medclip model? thanks a lot

**Comment by Kaushalya** [comment]
Hi,
This is a JAX (Flax) model built based on  the Hugging Face model `FlaxPreTrainedModel`. You can easily load the model weights from the HF hub with
```
from medclip.modeling_hybrid_clip import FlaxHybridCLIP
model = FlaxHybridCLIP.from_pretrained("flax-community/medclip-roco")
```
You may have to write your own loader to load these wights into a Pytorch model.
