### ISSUE TITLE
lack of files in hdf

### ISSUE THREAD

**Issue by balibata** [Kaushalya/medclip#25]
I try to run your app.py, but I meet the problem of reading hdf file. I print out the data structure of image_embeddings_large.hdf, and I find out that it only contains the following structure:
<img width="222" alt="image" src="https://github.com/user-attachments/assets/3ae6d1d7-c34a-4a0e-8557-f76664331d7b">
And for current version, it seems that it is unable to read the hdf file with pd.read_hdf, I have to use h5py to read. Can I have your hdf or your exact version of python packages?

**Comment by Kaushalya** [comment]
Hi,
Pandas does not work yet with numpy>=2.0, first released on June 16th, 2024. So, I downgraded Numpy to the latest 1.x version `1.26.4`.

**Comment by Kaushalya** [comment]
Fixed with commit [6785716](https://github.com/Kaushalya/medclip/commit/6785716bf29421f59cf3fa60700533cc3a0621bc) . Please check yourself.

**Comment by balibata** [comment]
thanks a lot, I solved it now
