### ISSUE TITLE
How to save model in local

### ISSUE THREAD

**Issue by adarsh-dikhit** [Kaushalya/medclip#6]
How to save a model in local machine ?

**Comment by Kaushalya** [comment]
Hi,

The model weights are saved at the end of each epoch using the function `save_pretrained` of `PretrainedModel` class ([HuggingFace docs](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/model#transformers.PreTrainedModel.save_pretrained))
```
model.save_pretrained(
                training_args.output_dir,
                params=params,
                push_to_hub=training_args.push_to_hub,
                commit_message=f"Saving weights and logs of epoch {epoch+1}",
               )
```
If you set the argument `push_to_hub` to `False`, it will be saved only locally. Hope this helped.
